code --install-extension akamud.vscode-theme-onelight
code --install-extension alefragnani.Bookmarks
code --install-extension Angular.ng-template
code --install-extension be5invis.vscode-custom-css
code --install-extension bierner.lit-html
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.npm-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension davidbabel.vscode-simpler-icons
code --install-extension dbaeumer.vscode-eslint
code --install-extension dbankier.vscode-quick-select
code --install-extension DotJoshJohnson.xml
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension Equinusocio.vsc-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-todo-plus
code --install-extension ghmcadams.lintlens
code --install-extension hedinne.popping-and-locking-vscode
code --install-extension jamesmaj.easy-icons
code --install-extension jamiewest.theme-light-vs-mac
code --install-extension johnpapa.Angular2
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension michelemelluso.code-beautifier
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension Orta.vscode-jest
code --install-extension PKief.material-icon-theme
code --install-extension redhat.java
code --install-extension rifi2k.format-html-in-php
code --install-extension ritwickdey.LiveServer
code --install-extension robinbentley.sass-indented
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension sianglim.slim
code --install-extension stevencl.addDocComments
code --install-extension sysoev.language-stylus
code --install-extension teabyii.ayu
code --install-extension techer.open-in-browser
code --install-extension Tobermory.es6-string-html
code --install-extension tomoki1207.pdf
code --install-extension vincaslt.highlight-matching-tag
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension wesbos.theme-cobalt2
code --install-extension whizkydee.material-palenight-theme
code --install-extension Yummygum.city-lights-icon-vsc
code --install-extension yummygum.city-lights-theme
code --install-extension yzhang.markdown-all-in-one
code --install-extension zxh404.vscode-proto3
code --install-extension andys8.jest-snippets